### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lovexy-fun** [diogoduailibe/lzstring4j#5]
Example:
```java
LZString.decompressFromBase64("JYWw5g9ATFCcAsUIFYDMyoHZMQIwH0AOQzVAOgCsAHMAGlEhgSTQ22nwDZPFKb7w0OIhTosOVPmSwADDL50GQ5qLY54+ePBIKBjYSzHtk+TMjO6lTEa3ERO+LDuqLB1w2oiZNUToUtuBqp2hPioWJwB+iq27LBhqJyYUco2Rji4MmG48PIueqkedrgEuKiEyCnuwey4UESylflWQbEZkvCwsMnNgTHpeBp+mLBVrQO4JvA5efwt/Z64DuXITXN9aYveSX5jC8Whdbu90ZvF8ZywqD3rp0XsUFnwqCUKQA===");
```
Result:
```shell
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: index 111,length 111
	at java.base/java.lang.String.checkIndex(String.java:3278)
	at java.base/java.lang.StringUTF16.checkIndex(StringUTF16.java:1470)
	at java.base/java.lang.StringUTF16.charAt(StringUTF16.java:1267)
	at java.base/java.lang.String.charAt(String.java:695)
	at LZString.decompress(LZString.java:365)
	at LZString.decompressFromBase64(LZString.java:628)
	at Main.main(Main.java:17)
```

**Comment by diogoduailibe** [comment]
Hi @lovexy-fun. Thank's for sharing.

Could you confirm if the original String (before compression) was:

`img/22942/535277/1_8873.jpg,img/22942/535277/2_6642.jpg,img/22942/535277/3_5900.jpg,img/22942/535277/4_4487.jpg,img/22942/535277/5_7575.jpg,img/22942/535277/6_2787.jpg,img/22942/535277/7_4268.jpg,img/22942/535277/8_3276.jpg,img/22942/535277/9_3367.jpg,img/22942/535277/10_3140.jpg,img/22942/535277/11_1385.jpg,img/22942/535277/12_8905.jpg,img/22942/535277/13_4997.jpg,img/22942/535277/14_6879.jpg,img/22942/535277/15_4140.jpg,img/22942/535277/16_3855.jpg,img/22942/535277/17_6768.jpg,img/22942/535277/18_1268.jpg,img/22942/535277/19_6937.jpg,img/22942/535277/20_4311.jpg` 

If so, the base64 String generated by the Algorithm for this original String is: 

`JYWw5g9ATFCcAsUIFYDMyoHZMQIwH0AOQzVAOgCsAHMAGlEhgSTQ22nwDZPFKb7w0OIhTosOVPmSwADDL50GQ5qLY54+ePBIKBjYSzHtk+TMjO6lTEa3ERO+LDuqLB1w2oiZNUToUtuBqp2hPioWJwB+iq27LBhqJyYUco2Rji4MmG48PIueqkedrgEuKiEyCnuwey4UESylflWQbEZkvCwsMnNgTHpeBp+mLBVrQO4JvA5efwt/Z64DuXITXN9aYveSX5jC8Whdbu90ZvF8ZywqD3rp0XsUFnwqCUKQAAA=`

There is a slight difference between them, that could be caused by several reasons.

Could you tell how you generated this String? 

Thank's!

**Comment by lovexy-fun** [comment]
Hi @diogoduailibe diogoduailibe Thank you for your answer.
Yeah, that's it(String before compression).
I got base64 String from a website.The website uses [lz-string.min.js](https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.min.js).
When I try to generate the base64 String using the [lz-string.min.js](https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.min.js), I get `JYWw5g9ATFCcAsUIFYDMyoHZMQIwH0AOQzVAOgCsAHMAGlEhgSTQ22nwDZPFKb7w0OIhTosOVPmSwADDL50GQ5qLY54+ePBIKBjYSzHtk+TMjO6lTEa3ERO+LDuqLB1w2oiZNUToUtuBqp2hPioWJwB+iq27LBhqJyYUco2Rji4MmG48PIueqkedrgEuKiEyCnuwey4UESylflWQbEZkvCwsMnNgTHpeBp+mLBVrQO4JvA5efwt/Z64DuXITXN9aYveSX5jC8Whdbu90ZvF8ZywqD3rp0XsUFnwqCUKQA===`

**Comment by lovexy-fun** [comment]
This error may be the same as issue https://github.com/diogoduailibe/lzstring4j/issues/4

**Comment by lovexy-fun** [comment]
This error may be the same as issue https://github.com/diogoduailibe/lzstring4j/issues/4
